version: "3"
services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "task_database"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "task_user"
      POSTGRES_HOST_AUTH_METHODM: "trust"